using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ProximaX.Sirius.Chain.Sdk.Infrastructure.DTO {

  /// <summary>
  /// 
  /// </summary>
  [DataContract]
  public class Cosignature {
    /// <summary>
    /// The hash of parent aggregate transaction that has been signed by a cosignatory of the transaction.
    /// </summary>
    /// <value>The hash of parent aggregate transaction that has been signed by a cosignatory of the transaction.</value>
    [DataMember(Name="parentHash", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "parentHash")]
    public string ParentHash { get; set; }

    /// <summary>
    /// The signatures generated by signing the parent aggregate transaction hash.
    /// </summary>
    /// <value>The signatures generated by signing the parent aggregate transaction hash.</value>
    [DataMember(Name="signature", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "signature")]
    public string Signature { get; set; }

    /// <summary>
    /// The signer of the transaction.
    /// </summary>
    /// <value>The signer of the transaction.</value>
    [DataMember(Name="signer", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "signer")]
    public string Signer { get; set; }


    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class Cosignature {\n");
      sb.Append("  ParentHash: ").Append(ParentHash).Append("\n");
      sb.Append("  Signature: ").Append(Signature).Append("\n");
      sb.Append("  Signer: ").Append(Signer).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

}
}
