name: build

on:
  push:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '5.0.x' # The .NET SDK version to use

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  ${{ env.DOTNET_VERSION }}

    - name: Install Lib Dependencies
      run: dotnet restore "src/ProximaX.Sirius.Chain.Sdk/ProximaX.Sirius.Chain.Sdk.csproj"
     
    - name: Build code library
      run:  dotnet build "src/ProximaX.Sirius.Chain.Sdk/ProximaX.Sirius.Chain.Sdk.csproj" --configuration Release --no-restore
    
          
