name: build

on:
  push:
    branches: [ v0.7.0 ]
  pull_request:
    branches: [ v0.7.0 ]

env:
  DOTNET_VERSION: '5.0.x' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        dotnet-version: [env.DOTNET_VERSION]
    steps:
    - uses: actions/checkout@v2
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
     
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Nuget
      run: nuget restore ProximaX.Sirius.Chain.Sdk.sln
      
    - name: Build
      run: msbuild ProximaX.Sirius.Chain.Sdk.sln
