name: build

on:
  push:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '5.0.403' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ./ProximaX.Sirius.Chain.Sdk.sln 
      
    - name: Build
      run: dotnet build ./src/ProximaX.Sirius.Chain.Sdk/ProximaX.Sirius.Chain.Sdk.csproj --configuration Release --no-restore
