name: build

on:
  release:
    types: [published]

env:
  DOTNET_VERSION: '5.0.x' # The .NET SDK version to use

jobs:
  build:

    name: build-ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  ${{ env.DOTNET_VERSION }}
        source-url: https://nuget.pkg.github.com/proximax-storage/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
     
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Nuget
      run: nuget restore "src/ProximaX.Sirius.Chain.Sdk/ProximaX.Sirius.Chain.Sdk.csproj"
      
    - name: Build
      run: dotnet build "src/ProximaX.Sirius.Chain.Sdk/ProximaX.Sirius.Chain.Sdk.csproj" --configuration Release --no-restore

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./src/ProximaX.Sirius.Chain.Sdk/bin/Release/*.nupkg --skip-duplicate
